import streamlit as st
import os
import random
import re
from io import BytesIO
import requests
import numpy as np
import pandas as pd
from PIL import Image
import exifread
import pdfplumber
from docx import Document
from google.oauth2 import service_account
from google.cloud import texttospeech
import plotly.express as px
import plotly.graph_objs as go
import streamlit.components.v1 as components
from pydub import AudioSegment
import openai
import streamlit_authenticator as stauth
import yaml
from yaml.loader import SafeLoader
from googleapiclient.discovery import build
import bcrypt
import tempfile
import json
import seaborn as sns
import matplotlib.pyplot as plt
import database  # データベースモジュールをインポート
import time
from streamlit_lottie import st_lottie
from functools import lru_cache  # キャッシュ用ライブラリ
import gettext  # 多言語対応用ライブラリ

# -----------------------------------
# 1. 初期設定
# -----------------------------------
st.set_page_config(page_title="融合アプリ", page_icon="✨", layout="wide")

# 多言語対応設定
# サポートする言語のリスト
LANGUAGES = {
    "日本語": "ja",
    "English": "en",
    "Español": "es",  # スペイン語の例
    # 必要に応じて他の言語を追加
}

# デフォルト言語設定
DEFAULT_LANGUAGE = "日本語"

# 翻訳辞書の作成
translations = {
    "ja": {
        "Welcome": "ようこそ",
        "Login": "ログイン",
        "Logout": "ログアウト",
        "Register": "登録",
        "Username": "ユーザー名",
        "Password": "パスワード",
        "Confirm Password": "パスワード確認",
        "Name": "名前",
        "Email": "メールアドレス",
        "Submit": "送信",
        "Feedback": "フィードバック",
        "Send": "送信",
        "File Upload": "ファイルアップロード",
        "Upload": "アップロード",
        "Download": "ダウンロード",
        "Settings": "設定",
        "Profile": "プロフィール",
        "Activity Log": "アクティビティログ",
        "Dashboard": "ダッシュボード",
        "Select Language": "言語選択",
        "Theme Selection": "テーマ選択",
        "Dark Mode": "ダークモード",
        "Light Mode": "ライトモード",
        "File Upload": "ファイルアップロード",
        "Image URL for EXIF analysis:": "EXIF解析用画像URL:",
        "Upload Files:": "ファイルアップロード:",
        "Supports large text/image/URL analysis":"大規模テキスト/画像/URL解析をサポート",
        "Image Feature": "画像特徴",
        "Direct Input":"直接入力",
        "Use Uploaded Text":"アップロードされたテキストを使用",
        "Paste the text to synthesize into speech":"音声に合成するテキストを貼り付けてください",
        "Paste large amounts of text here (e.g., full book)":"ここに大量のテキストを貼り付けてください(例：書籍全体)",
        "Extracted Text (Partial):":"抽出されたテキスト（一部）:",
        "No uploaded text available.":"アップロードされたテキストはありません。",
        "Speaker Gender":"話者の性別",
        "default":"デフォルト",
        "male":"男性",
        "female":"女性",
        "neutral":"中性",
        "Execute Speech Synthesis":"音声合成を実行",
        "Synthesizing speech... This may take some time for large texts.":"音声合成中... 大量のテキストの場合、時間がかかる場合があります。",
        "Speech synthesis completed!":"音声合成が完了しました！",
        "Download MP3":"MP3をダウンロード",
        "Massive Text-to-Speech":"大規模テキスト音声合成",
        "EXIF Analysis & Visualization":"EXIF解析と可視化",
        "No EXIF data available: Please upload an image or provide a URL.":"EXIFデータがありません：画像をアップロードするか、URLを入力してください。",
        "EXIF Data Extraction Results":"EXIFデータ抽出結果",
        "Uploaded Image":"アップロードされた画像",
        "RGB Channel Manipulation":"RGBチャンネル操作",
        "Select Channels to Display:":"表示するチャンネルを選択：",
        "Red":"赤",
        "Green":"緑",
        "Blue":"青",
        "HSV Histogram":"HSVヒストグラム",
        "Color Distribution Sunburst":"カラー分布サンバースト",
        "3D Color Space Plot":"3D色空間プロット",
        "AI-based Image Classification":"AIベースの画像分類",
        "Classify Image":"画像を分類",
        "Classifying image...":"画像を分類中...",
        "Classification Results":"分類結果",
        "Download Image without EXIF Data":"EXIFデータなしで画像をダウンロード",
        "⇩ EXIF除去後の画像ダウンロード":"⇩ EXIF除去後の画像ダウンロード",
        "Auto-generated Commentary":"自動生成された解説",
        "Play Commentary Audio":"解説音声の再生",
        "Dashboard":"ダッシュボード",
        "Responding...":"応答中...",
        "Error":"エラー",
        "Error Occurred":"エラーが発生しました",
        "Feel free to ask anything, including EXIF, TTS, image analysis, color space, AI image classification, or general questions.":"EXIF、TTS、画像解析、色空間、AI画像分類、または一般的な質問など、お気軽にお尋ねください。",
        "Adjust Model Parameters":"モデルパラメータを調整",
        "Temperature":"温度",
        "Top P":"トップP",
        "Max New Tokens":"最大新規トークン",
        "Min New Tokens":"最小新規トークン",
        "Presence Penalty":"プレゼンスペナルティ",
        "Frequency Penalty":"頻度ペナルティ",
        "Stop Sequences":"ストップシーケンス",
        "User Dashboard": "ユーザーダッシュボード",
        "Masaki Kusaka's Link Collection": "草加 将樹のリンク集",
        "Contact Us":"お問い合わせ",
        "LinkedIn":"LinkedIn",
        "Hire me!":"雇ってください！",
        "An all-in-one ultimate app integrated into the world for the first time.":"世界で初めて統合されたオールインワンの究極アプリ。",
        "If you do not have an API token, please obtain one from [Replicate](https://replicate.com/account/api-tokens).":"APIトークンをお持ちでない場合は、[Replicate](https://replicate.com/account/api-tokens)から取得してください。",
        "Enter your Replicate API Token:":"Replicate APIトークンを入力してください:",
        "Replicate API token is not set or user is not logged in.":"Replicate APIトークンが設定されていないか、ユーザーがログインしていません。",
        "Image with EXIF data removed is ready for download.":"EXIFデータが削除された画像はダウンロード可能です。",
        "Commentary audio playback completed.":"解説音声の再生が完了しました。",
        "Executed speech synthesis.":"音声合成を実行しました。",
        "Downloaded image without EXIF data.":"EXIFデータなしの画像をダウンロードしました。",
        "Viewed dashboard.":"ダッシュボードを表示しました。",
        "Executed GPT conversation.":"GPT会話を実行しました。",
        "GPT conversation has been updated.":"GPT会話が更新されました。",
        "An error occurred during GPT conversation":"GPT会話中にエラーが発生しました。",
        "Submitted feedback.":"フィードバックを送信しました。",
        "Activity Log":"アクティビティログ",
        "Please provide your feedback or comments here.":"ここにフィードバックまたはコメントを入力してください。",
        "Please enter your feedback before submitting.":"送信する前にフィードバックを入力してください。",
        "Thank you for your feedback!":"フィードバックありがとうございます！",
        "Failed to submit feedback. Please log in again.":"フィードバックの送信に失敗しました。再度ログインしてください。",
        "Go to Dashboard": "ダッシュボードへ移動",
        "No repositories found.":"リポジトリが見つかりませんでした。",
        "Latest GitHub Repositories":"最新のGitHubリポジトリ",
        "No videos found.":"動画が見つかりませんでした。",
        "Latest YouTube Videos":"最新のYouTube動画",
        "YouTube API key is not set.":"YouTube APIキーが設定されていません。",
        "No activity logs available yet.":"まだアクティビティログはありません。",
        "Uploaded Images":"アップロードされた画像",
        "Generated Audio Files":"生成されたオーディオファイル",
        "Audio file management functionality is not yet implemented.":"オーディオファイル管理機能はまだ実装されていません。",
        "No uploaded images found.":"アップロードされた画像は見つかりませんでした。",
        "Download Image": "画像をダウンロード",
        "Classification Result": "分類結果",
        "Manage Data": "データ管理",
         "Edit Profile": "プロフィールを編集",
         "New Password": "新しいパスワード",
         "Confirm New Password": "新しいパスワードを確認",
         "Update Profile": "プロフィールを更新",
         "New passwords do not match.": "新しいパスワードが一致しません。",
         "Password has been updated.":"パスワードが更新されました。",
         "This email address is already in use.":"このメールアドレスは既に使用されています。",
         "Email address has been updated.":"メールアドレスが更新されました。",
         "Name has been updated.":"名前が更新されました。",
        "Notification Settings":"通知設定",
        "Edit Notification Settings": "通知設定を編集",
        "Receive notifications when speech synthesis is complete": "音声合成完了時に通知を受け取る",
        "Receive notifications when image classification is complete": "画像分類完了時に通知を受け取る",
        "Receive notifications when feedback is submitted": "フィードバックが送信されたときに通知を受け取る",
         "Update Notification Settings":"通知設定を更新",
        "Updated notification settings.": "通知設定を更新しました。",
        "Executed image classification.":"画像分類を実行しました。",
        "Please log in.":"ログインしてください。",
        "Incorrect username or password.": "ユーザー名またはパスワードが間違っています。",
         "The URL does not point to an image.":"URLは画像を指していません。",
          "Failed to retrieve image from the URL.":"URLから画像を取得できませんでした。",
         "Image type is not supported.":"画像タイプがサポートされていません。",
         "Please fill in all fields.":"すべてのフィールドを入力してください。",
        "This username already exists. Please choose another one.":"このユーザー名は既に存在します。別のものを選んでください。",
        "This email address is already registered. Please use another email address.":"このメールアドレスは既に登録されています。別のメールアドレスを使用してください。",
        "Registration completed. Please log in.":"登録が完了しました。ログインしてください。",
        "Welcome": "ようこそ",
        "Chat Log":"チャットログ",
        "Clear Chat History":"チャット履歴をクリア",
       "Chat history has been cleared!":"チャット履歴がクリアされました！",
         "チャット履歴をクリアしました！":"チャット履歴をクリアしました！",
        "ここは人類史上初の究極融合アプリ。チャット履歴をクリアしました。再び新たなる時代へ踏み出そう。":"ここは人類史上初の究極融合アプリ。チャット履歴をクリアしました。再び新たなる時代へ踏み出そう。",
         "管理者用フィードバック閲覧": "管理者用フィードバック閲覧",
        "まだフィードバックがありません。": "まだフィードバックがありません。",
        "不明なユーザー":"不明なユーザー",
        "管理者用画像分類結果閲覧":"管理者用画像分類結果閲覧",
        "まだ画像分類結果がありません。":"まだ画像分類結果がありません。",
        "ユーザー名": "ユーザー名",
         "日時":"日時",
        "フィードバック":"フィードバック",
        "画像": "画像",
        "分類結果":"分類結果",
         "カメラモデルの種類":"カメラモデルの種類",
         "露出時間の平均 (秒)":"露出時間の平均 (秒)",
         "計算不能":"計算不能",
         "ISO感度の平均":"ISO感度の平均",
         "焦点距離の平均 (mm)":"焦点距離の平均 (mm)",
          "数":"数",
           "露出時間の分布":"露出時間の分布",
           "露出時間 (秒)":"露出時間 (秒)",
            "ISO感度の分布":"ISO感度の分布",
            "ISO感度":"ISO感度",
            "チャット履歴をクリアしますか？":"チャット履歴をクリアしますか？",
             "Clear":"クリア",
             "Cancel": "キャンセル",
              "User Activities":"ユーザーアクティビティ",
             "Delete Account":"アカウントを削除",
             "Are you sure you want to delete your account?":"アカウントを削除してもよろしいですか？",
              "Permanently delete your account.":"アカウントを完全に削除します。",
              "Confirm Delete":"削除確認",
    },
    "en": {
        "Welcome": "Welcome",
        "Login": "Login",
        "Logout": "Logout",
        "Register": "Register",
        "Username": "Username",
        "Password": "Password",
        "Confirm Password": "Confirm Password",
        "Name": "Name",
        "Email": "Email",
        "Submit": "Submit",
        "Feedback": "Feedback",
        "Send": "Send",
        "File Upload": "File Upload",
        "Upload": "Upload",
        "Download": "Download",
        "Settings": "Settings",
        "Profile": "Profile",
        "Activity Log": "Activity Log",
        "Dashboard": "Dashboard",
        "Select Language": "Select Language",
        "Theme Selection": "Theme Selection",
        "Dark Mode": "Dark Mode",
        "Light Mode": "Light Mode",
        "File Upload": "File Upload",
        "Image URL for EXIF analysis:": "Image URL for EXIF analysis:",
        "Upload Files:": "Upload Files:",
         "Supports large text/image/URL analysis":"Supports large text/image/URL analysis",
         "Image Feature": "Image Feature",
         "Direct Input":"Direct Input",
        "Use Uploaded Text":"Use Uploaded Text",
        "Paste the text to synthesize into speech":"Paste the text to synthesize into speech",
        "Paste large amounts of text here (e.g., full book)":"Paste large amounts of text here (e.g., full book)",
        "Extracted Text (Partial):":"Extracted Text (Partial):",
        "No uploaded text available.":"No uploaded text available.",
        "Speaker Gender":"Speaker Gender",
        "default":"default",
        "male":"male",
        "female":"female",
        "neutral":"neutral",
         "Execute Speech Synthesis":"Execute Speech Synthesis",
         "Synthesizing speech... This may take some time for large texts.":"Synthesizing speech... This may take some time for large texts.",
         "Speech synthesis completed!":"Speech synthesis completed!",
         "Download MP3":"Download MP3",
         "Massive Text-to-Speech":"Massive Text-to-Speech",
         "EXIF Analysis & Visualization":"EXIF Analysis & Visualization",
        "No EXIF data available: Please upload an image or provide a URL.":"No EXIF data available: Please upload an image or provide a URL.",
        "EXIF Data Extraction Results":"EXIF Data Extraction Results",
         "Uploaded Image":"Uploaded Image",
        "RGB Channel Manipulation":"RGB Channel Manipulation",
         "Select Channels to Display:":"Select Channels to Display:",
         "Red":"Red",
         "Green":"Green",
         "Blue":"Blue",
        "HSV Histogram":"HSV Histogram",
         "Color Distribution Sunburst":"Color Distribution Sunburst",
         "3D Color Space Plot":"3D Color Space Plot",
         "AI-based Image Classification":"AI-based Image Classification",
        "Classify Image":"Classify Image",
         "Classifying image...":"Classifying image...",
        "Classification Results":"Classification Results",
        "Download Image without EXIF Data":"Download Image without EXIF Data",
        "⇩ EXIF除去後の画像ダウンロード":"⇩ Download Image without EXIF data",
        "Auto-generated Commentary":"Auto-generated Commentary",
        "Play Commentary Audio":"Play Commentary Audio",
        "Dashboard":"Dashboard",
        "Responding...":"Responding...",
        "Error":"Error",
         "Error Occurred":"Error Occurred",
         "Feel free to ask anything, including EXIF, TTS, image analysis, color space, AI image classification, or general questions.":"Feel free to ask anything, including EXIF, TTS, image analysis, color space, AI image classification, or general questions.",
         "Adjust Model Parameters":"Adjust Model Parameters",
        "Temperature":"Temperature",
         "Top P":"Top P",
         "Max New Tokens":"Max New Tokens",
         "Min New Tokens":"Min New Tokens",
        "Presence Penalty":"Presence Penalty",
         "Frequency Penalty":"Frequency Penalty",
         "Stop Sequences":"Stop Sequences",
        "User Dashboard": "User Dashboard",
         "Masaki Kusaka's Link Collection": "Masaki Kusaka's Link Collection",
        "Contact Us":"Contact Us",
         "LinkedIn":"LinkedIn",
         "Hire me!":"Hire me!",
        "An all-in-one ultimate app integrated into the world for the first time.":"An all-in-one ultimate app integrated into the world for the first time.",
        "If you do not have an API token, please obtain one from [Replicate](https://replicate.com/account/api-tokens).":"If you do not have an API token, please obtain one from [Replicate](https://replicate.com/account/api-tokens).",
        "Enter your Replicate API Token:":"Enter your Replicate API Token:",
         "Replicate API token is not set or user is not logged in.":"Replicate API token is not set or user is not logged in.",
         "Image with EXIF data removed is ready for download.":"Image with EXIF data removed is ready for download.",
          "Commentary audio playback completed.":"Commentary audio playback completed.",
          "Executed speech synthesis.":"Executed speech synthesis.",
         "Downloaded image without EXIF data.":"Downloaded image without EXIF data.",
         "Viewed dashboard.":"Viewed dashboard.",
         "Executed GPT conversation.":"Executed GPT conversation.",
        "GPT conversation has been updated.":"GPT conversation has been updated.",
         "An error occurred during GPT conversation":"An error occurred during GPT conversation",
         "Submitted feedback.":"Submitted feedback.",
         "Activity Log":"Activity Log",
        "Please provide your feedback or comments here.":"Please provide your feedback or comments here.",
        "Please enter your feedback before submitting.":"Please enter your feedback before submitting.",
        "Thank you for your feedback!":"Thank you for your feedback!",
         "Failed to submit feedback. Please log in again.":"Failed to submit feedback. Please log in again.",
        "Go to Dashboard": "Go to Dashboard",
         "No repositories found.":"No repositories found.",
         "Latest GitHub Repositories":"Latest GitHub Repositories",
         "No videos found.":"No videos found.",
        "Latest YouTube Videos":"Latest YouTube Videos",
         "YouTube API key is not set.":"YouTube API key is not set.",
        "No activity logs available yet.":"No activity logs available yet.",
         "Uploaded Images":"Uploaded Images",
         "Generated Audio Files":"Generated Audio Files",
         "Audio file management functionality is not yet implemented.":"Audio file management functionality is not yet implemented.",
        "No uploaded images found.":"No uploaded images found.",
         "Download Image": "Download Image",
         "Classification Result": "Classification Result",
         "Manage Data": "Manage Data",
         "Edit Profile": "Edit Profile",
         "New Password": "New Password",
         "Confirm New Password": "Confirm New Password",
         "Update Profile": "Update Profile",
        "New passwords do not match.": "New passwords do not match.",
        "Password has been updated.":"Password has been updated.",
         "This email address is already in use.":"This email address is already in use.",
        "Email address has been updated.":"Email address has been updated.",
        "Name has been updated.":"Name has been updated.",
        "Notification Settings":"Notification Settings",
        "Edit Notification Settings": "Edit Notification Settings",
        "Receive notifications when speech synthesis is complete": "Receive notifications when speech synthesis is complete",
        "Receive notifications when image classification is complete": "Receive notifications when image classification is complete",
        "Receive notifications when feedback is submitted": "Receive notifications when feedback is submitted",
         "Update Notification Settings":"Update Notification Settings",
        "Updated notification settings.": "Updated notification settings.",
         "Executed image classification.":"Executed image classification.",
          "Please log in.":"Please log in.",
         "Incorrect username or password.": "Incorrect username or password.",
         "The URL does not point to an image.":"The URL does not point to an image.",
        "Failed to retrieve image from the URL.":"Failed to retrieve image from the URL.",
         "Image type is not supported.":"Image type is not supported.",
        "Please fill in all fields.":"Please fill in all fields.",
        "This username already exists. Please choose another one.":"This username already exists. Please choose another one.",
        "This email address is already registered. Please use another email address.":"This email address is already registered. Please use another email address.",
        "Registration completed. Please log in.":"Registration completed. Please log in.",
        "Welcome": "Welcome",
        "Chat Log":"Chat Log",
        "Clear Chat History":"Clear Chat History",
        "Chat history has been cleared!":"Chat history has been cleared!",
        "チャット履歴をクリアしました！":"Chat history has been cleared!",
        "ここは人類史上初の究極融合アプリ。チャット履歴をクリアしました。再び新たなる時代へ踏み出そう。":"This is the first ultimate fusion app in human history. The chat history has been cleared. Let's step into a new era again.",
         "管理者用フィードバック閲覧": "Admin Feedback View",
         "まだフィードバックがありません。": "No feedback yet.",
          "不明なユーザー":"Unknown User",
         "管理者用画像分類結果閲覧":"Admin Image Classification View",
         "まだ画像分類結果がありません。": "No image classification results yet.",
        "ユーザー名": "Username",
        "日時":"Timestamp",
        "フィードバック":"Feedback",
         "画像": "Image",
         "分類結果":"Classification Result",
          "カメラモデルの種類":"Camera Model Types",
        "露出時間の平均 (秒)":"Average Exposure Time (seconds)",
        "計算不能":"Cannot calculate",
         "ISO感度の平均":"Average ISO Speed",
         "焦点距離の平均 (mm)":"Average Focal Length (mm)",
         "数":"Count",
        "露出時間の分布":"Exposure Time Distribution",
        "露出時間 (秒)":"Exposure Time (seconds)",
        "ISO感度の分布":"ISO Speed Distribution",
        "ISO感度":"ISO Speed",
         "チャット履歴をクリアしますか？":"Clear chat history?",
           "Clear":"Clear",
             "Cancel": "Cancel",
              "User Activities":"User Activities",
             "Delete Account":"Delete Account",
             "Are you sure you want to delete your account?":"Are you sure you want to delete your account?",
              "Permanently delete your account.":"Permanently delete your account.",
              "Confirm Delete":"Confirm Delete",
    },
    "es": {
        "Welcome": "Bienvenido",
        "Login": "Iniciar sesión",
        "Logout": "Cerrar sesión",
        "Register": "Registrarse",
        "Username": "Nombre de usuario",
        "Password": "Contraseña",
        "Confirm Password": "Confirmar contraseña",
        "Name": "Nombre",
        "Email": "Correo electrónico",
        "Submit": "Enviar",
        "Feedback": "Retroalimentación",
        "Send": "Enviar",
        "File Upload": "Carga de archivos",
        "Upload": "Subir",
        "Download": "Descargar",
        "Settings": "Configuraciones",
        "Profile": "Perfil",
        "Activity Log": "Registro de actividad",
        "Dashboard": "Tablero",
        "Select Language": "Seleccionar idioma",
        "Theme Selection": "Selección de tema",
        "Dark Mode":"Modo Oscuro",
        "Light Mode":"Modo Claro",
        "File Upload": "Carga de archivos",
        "Image URL for EXIF analysis:": "URL de imagen para análisis EXIF:",
        "Upload Files:": "Subir archivos:",
        "Supports large text/image/URL analysis":"Soporta análisis de texto/imagen/URL grandes",
         "Image Feature": "Característica de la Imagen",
        "Direct Input":"Entrada Directa",
        "Use Uploaded Text":"Usar texto subido",
        "Paste the text to synthesize into speech":"Pegue el texto para sintetizar en voz",
        "Paste large amounts of text here (e.g., full book)":"Pegue grandes cantidades de texto aquí (ej., libro completo)",
        "Extracted Text (Partial):":"Texto Extraído (Parcial):",
        "No uploaded text available.":"No hay texto subido disponible.",
         "Speaker Gender":"Género del hablante",
        "default":"predeterminado",
        "male":"masculino",
        "female":"femenino",
        "neutral":"neutral",
        "Execute Speech Synthesis":"Ejecutar síntesis de voz",
         "Synthesizing speech... This may take some time for large texts.":"Sintetizando voz... Esto puede tomar algún tiempo para textos grandes.",
        "Speech synthesis completed!":"¡Síntesis de voz completada!",
         "Download MP3":"Descargar MP3",
         "Massive Text-to-Speech":"Texto a voz masivo",
         "EXIF Analysis & Visualization":"Análisis y Visualización EXIF",
         "No EXIF data available: Please upload an image or provide a URL.":"No hay datos EXIF disponibles: por favor suba una imagen o proporcione una URL.",
         "EXIF Data Extraction Results":"Resultados de Extracción de Datos EXIF",
         "Uploaded Image":"Imagen Subida",
         "RGB Channel Manipulation":"Manipulación de Canal RGB",
         "Select Channels to Display:":"Seleccione los canales a mostrar:",
         "Red":"Rojo",
        "Green":"Verde",
        "Blue":"Azul",
        "HSV Histogram":"Histograma HSV",
         "Color Distribution Sunburst":"Distribución de Color Sunburst",
        "3D Color Space Plot":"Gráfico de Espacio de Color 3D",
        "AI-based Image Classification":"Clasificación de Imagen basada en IA",
        "Classify Image":"Clasificar Imagen",
        "Classifying image...":"Clasificando imagen...",
        "Classification Results":"Resultados de Clasificación",
        "Download Image without EXIF Data":"Descargar Imagen sin Datos EXIF",
        "⇩ EXIF除去後の画像ダウンロード":"⇩ Descargar Imagen sin EXIF",
        "Auto-generated Commentary":"Comentario autogenerado",
        "Play Commentary Audio":"Reproducir Audio de Comentario",
        "Dashboard":"Tablero",
        "Responding...":"Respondiendo...",
        "Error":"Error",
         "Error Occurred":"Ocurrió un Error",
         "Feel free to ask anything, including EXIF, TTS, image analysis, color space, AI image classification, or general questions.":"Siéntase libre de preguntar cualquier cosa, incluyendo EXIF, TTS, análisis de imagen, espacio de color, clasificación de imagen por IA, o preguntas generales.",
         "Adjust Model Parameters":"Ajustar Parámetros del Modelo",
        "Temperature":"Temperatura",
         "Top P":"Top P",
         "Max New Tokens":"Máximo de Nuevos Tokens",
        "Min New Tokens":"Mínimo de Nuevos Tokens",
         "Presence Penalty":"Penalización de Presencia",
        "Frequency Penalty":"Penalización de Frecuencia",
        "Stop Sequences":"Secuencias de Parada",
        "User Dashboard": "Tablero de Usuario",
        "Masaki Kusaka's Link Collection": "Colección de Enlaces de Masaki Kusaka",
        "Contact Us":"Contáctenos",
        "LinkedIn":"LinkedIn",
        "Hire me!":"¡Contrátame!",
        "An all-in-one ultimate app integrated into the world for the first time.":"Una aplicación todo en uno integrada en el mundo por primera vez.",
        "If you do not have an API token, please obtain one from [Replicate](https://replicate.com/account/api-tokens).":"Si no tiene un token de API, por favor obtenga uno de [Replicate](https://replicate.com/account/api-tokens).",
         "Enter your Replicate API Token:":"Ingrese su Token de API de Replicate:",
         "Replicate API token is not set or user is not logged in.":"El token de API de Replicate no está configurado o el usuario no ha iniciado sesión.",
        "Image with EXIF data removed is ready for download.":"La imagen sin datos EXIF está lista para descargar.",
        "Commentary audio playback completed.":"Reproducción de audio de comentario completada.",
         "Executed speech synthesis.":"Síntesis de voz ejecutada.",
         "Downloaded image without EXIF data.":"Imagen sin datos EXIF descargada.",
        "Viewed dashboard.":"Tablero visualizado.",
        "Executed GPT conversation.":"Conversación GPT ejecutada.",
        "GPT conversation has been updated.":"Conversación GPT actualizada.",
         "An error occurred during GPT conversation":"Ocurrió un error durante la conversación GPT",
        "Submitted feedback.":"Retroalimentación enviada.",
         "Activity Log":"Registro de Actividad",
        "Please provide your feedback or comments here.":"Por favor, proporcione su retroalimentación o comentarios aquí.",
        "Please enter your feedback before submitting.":"Por favor, ingrese su retroalimentación antes de enviar.",
        "Thank you for your feedback!":"¡Gracias por su retroalimentación!",
        "Failed to submit feedback. Please log in again.":"Error al enviar la retroalimentación. Por favor, inicie sesión de nuevo.",
        "Go to Dashboard": "Ir al Tablero",
         "No repositories found.":"No se encontraron repositorios.",
         "Latest GitHub Repositories":"Últimos Repositorios de GitHub",
        "No videos found.":"No se encontraron videos.",
        "Latest YouTube Videos":"Últimos Videos de YouTube",
         "YouTube API key is not set.":"La clave API de YouTube no está configurada.",
        "No activity logs available yet.":"Aún no hay registros de actividad disponibles.",
        "Uploaded Images":"Imágenes Subidas",
        "Generated Audio Files":"Archivos de Audio Generados",
         "Audio file management functionality is not yet implemented.":"La funcionalidad de gestión de archivos de audio aún no está implementada.",
         "No uploaded images found.":"No se encontraron imágenes subidas.",
         "Download Image": "Descargar Imagen",
         "Classification Result": "Resultado de Clasificación",
         "Manage Data": "Gestionar Datos",
          "Edit Profile": "Editar Perfil",
         "New Password": "Nueva Contraseña",
         "Confirm New Password": "Confirmar Nueva Contraseña",
         "Update Profile": "Actualizar Perfil",
         "New passwords do not match.":"Las nuevas contraseñas no coinciden.",
        "Password has been updated.":"La contraseña ha sido actualizada.",
         "This email address is already in use.":"Esta dirección de correo electrónico ya está en uso.",
         "Email address has been updated.":"La dirección de correo electrónico ha sido actualizada.",
         "Name has been updated.":"El nombre ha sido actualizado.",
        "Notification Settings":"Configuraciones de Notificación",
        "Edit Notification Settings": "Editar Configuraciones de Notificación",
        "Receive notifications when speech synthesis is complete": "Recibir notificaciones cuando la síntesis de voz esté completa",
        "Receive notifications when image classification is complete": "Recibir notificaciones cuando la clasificación de imagen esté completa",
        "Receive notifications when feedback is submitted": "Recibir notificaciones cuando se envíe retroalimentación",
         "Update Notification Settings":"Actualizar Configuraciones de Notificación",
         "Updated notification settings.": "Configuraciones de notificación actualizadas.",
        "Executed image classification.":"Clasificación de imagen ejecutada.",
          "Please log in.":"Por favor, inicie sesión.",
         "Incorrect username or password.":"Nombre de usuario o contraseña incorrectos.",
         "The URL does not point to an image.":"La URL no apunta a una imagen.",
         "Failed to retrieve image from the URL.":"Error al recuperar la imagen de la URL.",
         "Image type is not supported.":"Tipo de imagen no soportado.",
         "Please fill in all fields.":"Por favor, complete todos los campos.",
         "This username already exists. Please choose another one.":"Este nombre de usuario ya existe. Por favor, elija otro.",
         "This email address is already registered. Please use another email address.":"Esta dirección de correo electrónico ya está registrada. Por favor, use otra dirección de correo electrónico.",
        "Registration completed. Please log in.":"Registro completado. Por favor, inicie sesión.",
        "Welcome": "Bienvenido",
         "Chat Log":"Registro de Chat",
         "Clear Chat History":"Limpiar Historial de Chat",
        "Chat history has been cleared!":"¡El historial de chat ha sido limpiado!",
          "チャット履歴をクリアしました！":"¡Historial de chat limpiado!",
         "ここは人類史上初の究極融合アプリ。チャット履歴をクリアしました。再び新たなる時代へ踏み出そう。":"Esta es la primera aplicación de fusión definitiva en la historia de la humanidad. El historial de chat se ha borrado. Demos un paso hacia una nueva era de nuevo.",
         "管理者用フィードバック閲覧": "Vista de Retroalimentación del Administrador",
         "まだフィードバックがありません。": "Aún no hay retroalimentación.",
         "不明なユーザー":"Usuario Desconocido",
         "管理者用画像分類結果閲覧":"Vista de Clasificación de Imagen del Administrador",
          "まだ画像分類結果がありません。": "Aún no hay resultados de clasificación de imágenes.",
        "ユーザー名": "Nombre de usuario",
        "日時":"Fecha y Hora",
        "フィードバック":"Retroalimentación",
        "画像": "Imagen",
        "分類結果":"Resultado de Clasificación",
         "カメラモデルの種類":"Tipos de Modelos de Cámara",
          "露出時間の平均 (秒)":"Tiempo de Exposición Promedio (segundos)",
         "計算不能":"No se puede calcular",
         "ISO感度の平均":"Velocidad ISO Promedio",
        "焦点距離の平均 (mm)":"Distancia Focal Promedio (mm)",
         "数":"Conteo",
         "露出時間の分布":"Distribución del Tiempo de Exposición",
          "露出時間 (秒)":"Tiempo de Exposición (segundos)",
          "ISO感度の分布":"Distribución de la Velocidad ISO",
          "ISO感度":"Velocidad ISO",
          "チャット履歴をクリアしますか
